# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SenjaBina' do
  pod 'AppCenter/Push', '~> 1.12.0'
  pod 'AppCenter/Crashes', '~> 1.12.0'
  pod 'AppCenter/Analytics', '~> 1.12.0'
  pod 'AppCenterReactNativeShared', '~> 1.11.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SenjaBina

  

  platform :ios, '9.0'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'SenjaBinaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SenjaBina-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SenjaBina-tvOS

  target 'SenjaBina-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
